### ISSUE TITLE
http://illposed.net/shim-13.3-1.x86_64.rpm HTTP 404

### ISSUE THREAD

**Issue by pranasblk** [Paradigm4/shim#47]
Broken link. Would you mind pointing to correct location?

**Comment by bwlewis** [comment]
You can see all the old binary packages here:

https://github.com/Paradigm4/shim/tree/gh-pages


I'm not sure where the broken link is that you're referring to...

**Comment by bwlewis** [comment]
Did that help?

**Comment by pranasblk** [comment]
All good, I searched whole repo for "http://illposed.net/shim-13.3-1.x86_64.rpm" and seems like the old document has been updated.
