### ISSUE TITLE
Interactive Query displays result multiple times

### ISSUE THREAD

**Issue by rvernica** [Paradigm4/shim#51]
When using Interactive Query, Shim prints the result of each query twice. This is fine for one query, but when multiple queries are used, the order is mixed and hard to read.

For example, one query looks like this:
![shim-1-query](https://cloud.githubusercontent.com/assets/241185/16969667/57906246-4dcb-11e6-8940-9bbd7848da45.png)

For queries look like this:
![shim-4-queries](https://cloud.githubusercontent.com/assets/241185/16969672/657dbef8-4dcb-11e6-97ce-35958a10a176.png)

Notice how the order of the results is:
- Query 1
- Query 2
- Query 3
- Query 1
- Query 4...

I am using Shim installed from the `deb` package provided with the `15.12` AMI image:

```
# apt-cache show shim
Package: shim
Status: install ok installed
Priority: extra
Section: default
Installed-Size: 4129
Maintainer: <blewis@paradigm4.com>
Architecture: amd64
Version: 15.12
Provides: shim
Depends: libssl-dev
Conffiles:
 /etc/init.d/shimsvc 984810d7c80a32f722c8d3223e9df31b
Description: Unofficial SciDB HTTP service
Description-md5: 781385535c734f5faab5c0ff00b81773
License: AGPLv3
Vendor: Paradigm4
Homepage: https://github.com/Paradigm4/shim
```

**Comment by rvernica** [comment]
It seems that this is intentional (at least for now). Each result is fetched twice, see [L303](https://github.com/Paradigm4/shim/blob/40082008bf0a8f9a1d30b257b7cc8285cff910ec/wwwroot/js/scidb_query.js#L303)

Moreover, when there are multiple queries, they are launched when the result from the previous queries is read ([L284](https://github.com/Paradigm4/shim/blob/40082008bf0a8f9a1d30b257b7cc8285cff910ec/wwwroot/js/scidb_query.js#L284) and [L296](https://github.com/Paradigm4/shim/blob/40082008bf0a8f9a1d30b257b7cc8285cff910ec/wwwroot/js/scidb_query.js#L296)). This might lead to having later queries executed multiple times. In the second screenshot above, the result for the forth query is printed four times because it is executed twice.

**Comment by bwlewis** [comment]
Yes, I think we're on the verge of ditching this whole thing (shim) and hopefully replacing it with something better, so probably won't fix it. Shim's a 5 year old hack that really should've been replaced long ago...
