### ISSUE TITLE
[Long-running shim session] /cancel does not work

### ISSUE THREAD

**Issue by ksens** [Paradigm4/shim#69]
@rvernica 

I am able to replicate a `/cancel` error using `curl` as follows. 

## Pre-work 

1. Some characters below clash with URL formatting. So I create an array for my test

```sh
iquery -aq "store(build(<t:uint64>[i=1:1,3,0],i), temp)"
```
2. Load the `superfunpack` [plugin](https://github.com/Paradigm4/superfunpack). 

## Recreate error as follows

```sh
PASSWORD=Paradigm4
USER=root
host=localhost
port=8083

api_url="https://${host}:${port}"
curl_cmd="curl --silent --show-error --insecure"


echo "list..."
id=$($curl_cmd "$api_url/new_session?user=${USER}&password=${PASSWORD}")
query="apply(temp,zzz,sleep(10))"
$curl_cmd "$api_url/execute_query?id=${id}&query=${query}&save=dcsv" &
# Above runs a command for 10 seconds and returns control

$curl_cmd "$api_url/cancel?id=${id}"
```

The shim log shows the following
```sh
Nov  8 14:22:18 ksen-VirtualBox shim: cancel_query session iu531gvyx99bwdekbutaj889ee4dx9wf queryid 0.1510168929209759735
Nov  8 14:22:18 ksen-VirtualBox shim: cancel_query SystemException in file: src/network/ClientMessageHandleJob.cpp function: dispatch line: 1242#012Error id: scidb::SCIDB_SE_NETWORK::SCIDB_LE_AUTHENTICATION_ERROR#012Error description: Network error. Authentication error reason='not authenticated'.
Nov  8 14:22:19 ksen-VirtualBox shim: execute_query iu531gvyx99bwdekbutaj889ee4dx9wf done
```

I think the relevant section in `shim.c` is
https://github.com/Paradigm4/shim/blob/session-auth/src/shim.c#L360

**Comment by rvernica** [comment]
This is an interesting use-case. Here is what is happening:

1. When you issue the initial `/new_session` request a SciDB connection object is created by Shim and maintained in the session instance. The actual credentials are discarded.
1. When you issue the `/execute_query` request, the SciDB connection created in (1) is used to run the query. This request blocks, so you use `&` to send it in the background.
1. When you issue the `/cancel` request, the SciDB connection stored in the session can't actually be used as it is being used by the blocking request from (2). In fact, even a lock is taken on the session instance by the `/execute_query` request, lock which will be released when the execution completes. So, what Shim has to do is create a new SciDB connection, but it has not credentials, hence the `not authenticated` error.

Now, there are three ways to go around this:
1. Use the old API and provide the user/password credentials in the `/cancel` request. So, do `/cancel?id=...&user=...&password=...`. **This works right now.**
1. Shim could store the credentials in the session instance. So, when a `/cancel` request is made, the credentials can be used to create a new SciDB connection and issue the `cancel()` query. Note, that one of the advantages of "long running" Shim sessions is that client libraries (SciDBR, SciDB-Py) do not have to store credentials. We are now storing the credentials in Shim.
1. When a `/new_session` request is made, Shim could create two SciDB connections. The first one will be used for `/execute_query`, the second one for `/cancel`.

**Comment by apoliakov** [comment]
Hmm... interesting things we're discovering.
I prefer 2. Your thoughts?

**Comment by rvernica** [comment]
I would prefer 1. `/cancel` can't be used in interactive sessions anyway, since the `/execute_query` request would block. So, one would have to open a new "terminal" and copy the session ID manually. Then, he/she might provide the credentials as well.

Moreover, I think it is cleaner not to store the credentials in Shim. It makes Shim more secure.

**Comment by ksens** [comment]
2 would shift the password storage insecurity hole from client to server. 

1 has a problem. Though I showed a simplified demo where the `/execute_query` releases control using `&`, the typical client scenario is different. For example, in scidbR, the internal call `scidbquery` has an `interrupt` slot. See https://github.com/Paradigm4/SciDBR/blob/master/R/internal.R#L471

With this, if one runs a long running query
```
iquery(db, "long_running_query()", return=TRUE/FALSE)
```
R waits for response. If at that time, the user presses ESC, it hits the piece of `interrupt` code linked above. In that case, the `/cancel` should be automatically called (i.e. without username-password). As @rvernica explained, it attempts to use the same locked session and fails. 

3 sounds like a better solution in this case i.e. `/cancel` would always attempt to use a special session slot.

**Comment by apoliakov** [comment]
My thinking was, (1) would not be a good thing since we want to have the behavior of "cancel-query-on-ctrl-c". Or when we're running RStudio or iPython, if there's a long running block, then hitting "stop" would cancel the query. We don't want to say "hey enter your password again" on Ctrl-C. So for that reason it seemed that (1) wasn't a good fit.

That leaves (2) or (3). 2 is less secure and 3 uses another session. Now - I haven't seen multiuser test results as to the effective maximum number of sessions yet. But I agree withy your point - so let's try (3) and see how it goes.

**Comment by rvernica** [comment]
Makes sense. I'll proceed with (3).

**Comment by ksens** [comment]
@rvernica 

Not sure if you are done with this, or if you are working on this. I noticed your commit message on this thread, so I updated shim and started testing. 

I still get this to fail in SciDBR. 

```R
db1 = scidbconnect(username = 'root', password = 'Paradigm4', protocol = 'https', port = 8083)
iquery(db1, "apply(build(<t: uint64>[i=1:1,3,0], i), zzz, sleep(10))", return = T)
# cancel mid-query
# the scidb query is not canceled
```

Shim logs show the following:
```sh
Nov 13 00:07:22 ksen-VirtualBox shim: execute_query s67a5xjka0kw7qdzraz9xqoo8tf08twg connected user root s->scidb[0] = 0x2b03300487e0 s->scidb[1] 7qdzraz9xqoo8tf08twg connected user root s->scidb[0] = 0x2b03300487e0 s->scidb[1] = 0x2b0330064220 save(apply(apply(build(<t: uint64>[i=1:1,3,0], i), zzz, sleep(10)), i,i),'/home/scidb/scidb_data_dir/0/0/shim_output_buf_1kIPKb',0,'(uint64 null,uint32 ,int64 )')
Nov 13 00:07:22 ksen-VirtualBox shim: execute_query id=s67a5xjka0kw7qdzraz9xqoo8tf08twg scidb queryid = 0.1510549642605232120
Nov 13 00:07:25 ksen-VirtualBox shim: /cancel
Nov 13 00:07:25 ksen-VirtualBox shim: cancel session s67a5xjka0kw7qdzraz9xqoo8tf08twg queryid 0.1510549642605232120
Nov 13 00:07:25 ksen-VirtualBox shim: cancel SystemException in file: src/network/ClientMessageHandleJob.cpp function: dispatch line: 1242#012Error id: scidb::SCIDB_SE_NETWORK::SCIDB_LE_AUTHENTICATION_ERROR#012Error description: Network error. Authentication error reason='not authenticated'.
Nov 13 00:07:32 ksen-VirtualBox shim: execute_query s67a5xjka0kw7qdzraz9xqoo8tf08twg done
```

**Comment by rvernica** [comment]
Oops, sorry about that. It should be working now. I just tired it from R using your example. You should see something along these lines:
```bash
Nov 13 06:23:21 shim: /execute_query
Nov 13 06:23:21 shim: execute_query for session id iu531gvyx99bwdekbutaj889ee4dx9wf
Nov 13 06:23:21 shim: execute_query iu531gvyx99bwdekbutaj889ee4dx9wf connected user root s->scidb[0] = 0x7f681404a2c0 s->scidb[1] = 0x7f681404a320 save(apply(apply(build(<t: uint64>[i=1:1,3,0], i), zzz, sleep(10)), i,i),'/tmp//shim_output_buf_DVlT5S',0,'(uint64 null,uint32 ,int64 )')
Nov 13 06:23:21 shim: execute_query id=iu531gvyx99bwdekbutaj889ee4dx9wf scidb queryid = 0.1510554201700850835

Nov 13 06:23:24 shim: /cancel
Nov 13 06:23:24 shim: cancel session iu531gvyx99bwdekbutaj889ee4dx9wf queryid 0.1510554201700850835
Nov 13 06:23:24 shim: cancel 

Nov 13 06:23:31 shim: execute_prepared_query error SystemException in file: src/query/Query.cpp function: handleAbort line: 647 Error id: scidb::SCIDB_SE_QPROC::SCIDB_LE_QUERY_CANCELLED Error description: Query processor error. Query 0.1510554201700850835 was cancelled. Failed query id: 0.1510554201700850835
```

**Comment by ksens** [comment]
Tested. Works OK. Closing issue.
