### ISSUE TITLE
Release session for server errors in /read* endpoints

### ISSUE THREAD

**Issue by rvernica** [Paradigm4/shim#70]
When server errors (e.g., memory allocation) occur in `/execute_query` endpoint, Shim releases the session. Should Shim also release the session when server errors occur in the `/read*` endpoints?

**Comment by ksens** [comment]
Sounds correct.

Which code branch(es) were you thinking about?

**Comment by rvernica** [comment]
I was thinking about the `session-auth` branch.

**Comment by ksens** [comment]
@rvernica sorry I was not clear when I asked about code branch(es). I meant to ask which code lines you thinking about... 

Also, on first scan, I did not find any session release calls in `readlines` or `readbytes`

https://github.com/Paradigm4/shim/blob/session-auth/src/shim.c#L929
https://github.com/Paradigm4/shim/blob/session-auth/src/shim.c#L812

**Comment by rvernica** [comment]
Right, the current code is *not* releasing the session on server errors in the `/read*` endpoints. I am proposing to add such a session release for these endpoints as well. This way they are consistent with the behavior of the `/execute_query` endpoint.

**Comment by ksens** [comment]
OK I understand now. Yes, please go ahead with adding this.
