### ISSUE TITLE
HTTP 4xx vs 5xx API

### ISSUE THREAD

**Issue by rvernica** [Paradigm4/shim#71]
On server errors (e.g., memory allocation), Shim returns an `HTTP 5xx` status code. Shim also releases the session. The client (cURL, SciDB-R, SciDB-Py) knows that on `HTTP 5xx` status codes it needs to get a new session (and possibly re-authenticate).

On client errors (e.g., query syntax error), Shim returns an `HTTP 4xx` status code. In this case Shim *does not* release the session. The session is valid and the client can reuse it with a new query/request.

Authentication errors (i.e., wrong credentials) are client errors, so Shim returns an `HTTP 401` status code. To be consistent, **should Shim keep the session?** The `s->conn` member is `NULL` and this is detected next time the `/execute_query` endpoint is used and the connection could be retried. Moreover, the client can provide a new set of credentials using the old `/execute_query?user=...&password=...` API. The new credentials will be used.

**Comment by rvernica** [comment]
Shim returns an `HTTP 500` status code for any `prepare_query` or `execute_prepared_query` calls in the `/execute_query` endpoint. If Shim is *not* going release the session for these errors, should an `HTTP 4xx` status code be returned?

**Comment by apoliakov** [comment]
It sounds like the consistent thing to do. Can you check SciDB-R? Last I checked the code didn't make decisions based on returned status codes - but I could be wrong.

**Comment by rvernica** [comment]
Oh, no, I don't think any of the client libraries are making decisions based on the return status code. But if we are consistent with the returned status codes in Shim, the libraries would be encouraged to do so.

**Comment by apoliakov** [comment]
Yes - so sounds like a good thing to do

**Comment by rvernica** [comment]
Here is a list of the error codes currently returned by Shim:

HTTP 4xx | Comments
--- | ---
400 | Invalid HTTP args, Empty upload file
401 | SciDB authentication error
404 | Session not found, Output not saved (`/read*`)
410 | EOF during `/readlines`
416 typo? | EOF during `/readbytes`

HTTP 5xx | Comments
--- | ---
500 | Out of memory, Query error (prepare/execute), Cannot open output buffer
503 | Cannot connect to SciDB, No session slot available
507 | Out of memory, Cannot `fstat` file

**Comment by rvernica** [comment]
I propose the following updated list (changes are highlighted):

HTTP 4xx | Comments
--- | ---
400 Bad Request | Invalid HTTP args, Empty upload file
401 Unauthorized | SciDB authentication error
404 Not Found | Session not found
406 Not Acceptable | **Query error (prepare/execute)**
410 Gone | **Output not saved (`/read*`)**
416 Request Range Not Satisfiable | **EOF during `/read*`**

HTTP 5xx | Comments
--- | ---
500 Internal Server Error | **Out of memory**, Cannot open output buffer, **Cannot `fstat` file**
502 Bad Gateway | **Cannot connect to SciDB**
503 Service Unavailable | No session slot available

Shim will release the session on any `HTTP 5xx` errors. If `HTTP 401` is returned in `/new_session`, no session gets created.

**Comment by ksens** [comment]
Looks good to me.

**Comment by apoliakov** [comment]
Agreed. Thanks a lot!

**Comment by rvernica** [comment]
Current progress:
- [x] Return `4xx` and `5xx` HTTP codes as listed [above](https://github.com/Paradigm4/shim/issues/71#issuecomment-343706679)
- [x] Script to test HTTP codes and returned messages
- [ ] Update function doc strings
- [ ] Update API documentation

**Comment by ksens** [comment]
@rvernica 

[For when you are back]

I got the following sequence to cause a crash in scidb. 

```sh
iquery -aq "store(build(<val:double>[i=0:3], random()), temp)"
{i} val
{0} 1.59977e+09
{1} 2.12576e+09
{2} 2.07888e+09
{3} 1.02081e+09

iquery -aq "filter(temp, i = NULL)"
SystemException in file: src/network/BaseConnection.h function: receive line: 171
Error id: scidb::SCIDB_SE_NETWORK::SCIDB_LE_CANT_SEND_RECEIVE
Error description: Network error. Cannot receive network message: Read failed: End of file (asio.misc:2).  An instance may be offline..
```

Version
```sh
scidb --version
SciDB Version: 17.1.2
Build Type: RelWithDebInfo
Commit: 674ebdc
Copyright (C) 2008-2017 SciDB, Inc.
```

We are fixing this via internal ticket 5967. The relevant part here is that shim returned a 406 (error in query execute) i.e. it expected the shim session to remain active. But scidb had crashed and the user actually needs to initiate a new connection. 

Let us discuss and see if there is a better status message for this case.

**Comment by rvernica** [comment]
I merged `session-auth` into `v17.x-session-auth` and tried this:
```
> curl "http://localhost:8080/execute_query?id=$id&query=filter(temp,i=NULL)"
SystemException in file: src/network/BaseConnection.h function: receive line: 171
Error id: scidb::SCIDB_SE_NETWORK::SCIDB_LE_CANT_SEND_RECEIVE
Error description: Network error. Cannot receive network message: Read failed: End of file (asio.misc:2).  An instance may be offline..
###
### The session is still valid
###
/> curl "http://localhost:8080/execute_query?id=$id&query=list()"
SystemException in file: src/network/BaseConnection.h function: receive line: 171
Error id: scidb::SCIDB_SE_NETWORK::SCIDB_LE_CANT_SEND_RECEIVE
Error description: Network error. Cannot receive network message: Read failed: End of file (asio.misc:2).  An instance may be offline..
```
So, the results are as expected.

If SciDB is restarted, the Shim session is still valid, but it results in the same error. I guess this is because the SciDB connection persists and has the "An instance may be offline..."-state. If a new session is created it works as expected.

Also, worth noticing, when an instance is offline, creating a new session and executing a query makes the `execute_query` request to freeze.
