### ISSUE TITLE
[session-auth branch] does not work for 17.1

### ISSUE THREAD

**Issue by ksens** [Paradigm4/shim#74]
@rvernica 

The customer install we are targeting for session-auth branch has 17.1. Running `make` results in error. 

I was able to resolve the error by copying the changes from [this branch](https://github.com/Paradigm4/Shim/tree/v17.x). Can you integrate these changes with the `session-auth` branch? 

The change I copied was this:

```sh
[ksenshar@awsacdnva1108 shim]$ git diff
diff --git a/src/client.cpp b/src/client.cpp
index b697e96..4519758 100644
--- a/src/client.cpp
+++ b/src/client.cpp
@@ -34,6 +34,7 @@ extern "C"
 }

 #include "SciDBAPI.h"
+#include "rbac/SessionProperties.h"

 using namespace std;
 using namespace scidb;
@@ -51,7 +52,8 @@ extern "C" void * scidbconnect(const char *host, int port, const char* username,
   {
       if(username == NULL || password == NULL)
       {
-          conn = db.connect(host, port);
+          scidb::SessionProperties props;
+          conn = db.connect(props, host, port);
       }
       else
       {
```

I am keeping these changes local right now. Would request you to review the code at link above, integrate on your end, and then push to Github. You might want to:

1. integrate all code changes from link above
2. test the code on scidb 16.9 and 17.1 well to see if we can support only one code branch

Just FYI -- higher priority is to support 17.1, as that is the immediate customer requirement.

**Comment by rvernica** [comment]
Branch `v17.x-session-auth` is compatible with `17.1` and has session authentication support.
