### ISSUE TITLE
Automated build tools for shim

### ISSUE THREAD

**Issue by ksens** [Paradigm4/shim#77]
@rvernica 

How difficult would it be to leverage Travis to build RPM-s and DEB packages for Shim automatically? And also record the commit tag in the version information? 

Currently, we manually build these for shim and upload to [this link](https://github.com/Paradigm4/shim/tree/gh-pages). Then we link to the relevant binaries on the shim [man page](https://github.com/Paradigm4/shim#installation-from-binary-packages). 

Disadvantages of the manual process:
- Cumbersome
- One major issue I see is that later, I cannot exactly place which exact commit of shim I installed at a customer machine. 

```sh
shim -version
# 17.1.2
```
i.e. it only ties to the scidb version 

Compare that with the scidb version (scidb binaries are automatically built)
```sh
scidb --version
# SciDB Version: 17.1.2
# Build Type: RelWithDebInfo
# Commit: 674ebdc
# Copyright (C) 2008-2017 SciDB, Inc.
```

The exact commit tag is present.

**Comment by bwlewis** [comment]
should be easy so long as you can provide the required scidb libraries. if
you're building scidb in travis now, then no problem.

**Comment by rvernica** [comment]
Shim now reports the git commit, for example:
```bash
> shim -v
SciDB Version: 16.9.6
Shim Commit: 8e0b6e9
```

**Comment by ksens** [comment]
@rvernica your commit solves the issue of having the commit tag in the version description. Also you mentioned that while Travis can be easily used to build DEB / RPM package, it does not solve the issue of how to host packages. 

The automated build issue will be available via @JAKinchen 's build scripts. Then we need to work on the deployment process with @martin-resnick . 

Just noting here for reference. It is OK to keep this ticket closed as the build / deploy procedure is applicable to multiple scidb github repos / plugins.
