### ISSUE TITLE
create a man page directory

### ISSUE THREAD

**Issue by forskning** [Paradigm4/shim#91]
Any opinion on creating in /opt/scidb/18.1 a man page directory?

mkdir -p "$(DESTDIR)$(SCIDB)/man/man1"

https://paradigm4.github.io/scidblog/scidb-installation/

One could add on the above webpage an 'export' line in .scidbrc

export MANPATH="$MANPATH:/opt/scidb/18.1/man"

or author for /etc/profile.d executable scidb.csh and scidb.sh files.

http://slackbuilds.org/templates/autotools-template.SlackBuild

There is a section on the above webpage about compressing man pages.

Incidentally I noticed from the extracted scidb-18.1-utils-11-1.x86_64.rpm that the binaries with the exception of indexmapper are stripped, whether that was intentional or not, the above cited webpage also has a section on stripping binaries and libraries.

**Comment by forskning** [comment]
@rvernica 

if there is no interest in creating a man page directory

and indifference as regards the shipping of an unstripped binary

can you recommend closing

**Comment by rvernica** [comment]
Thanks for the notes. Sorry for not getting to this earlier. Let me understand what you are suggesting:

1. Are you suggesting to create a man page with the contents of https://paradigm4.github.io/scidblog/scidb-installation/ ? I think that page is about installing and setting up SciDB. This project is about Shim, which is an add-on to SciDB. So, that content might not be the right content to have here.
2. I'm not sure I get your comment about stripped binaries. Could you explain more?

**Comment by forskning** [comment]
https://github.com/Paradigm4/shim/tree/master/man

1) I presume that shim.1 under the current installation approach is located on $MANPATH.

and rather it be located in /opt/scidb/18.1/man/man1

in the latter location one would need to append $MANPATH

2) It's common practice on Un*x to strip binaries, I presume it was an oversight that indexmapper wasn't stripped.

http://slackbuilds.org/templates/autotools-template.SlackBuild

find -print0 | xargs -0 file | grep -e "executable" -e "shared object" | grep ELF \
  | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true
