### ISSUE TITLE
Error: Too many open files

### ISSUE THREAD

**Issue by ksens** [Paradigm4/shim#93]
@rvernica 

Getting the following error at one of the customer sites when trying to access shim:

```
# Error 500: Internal Server Error
# fopen(/var/lib/shim/wwwroot/index.html): Too many open files
```

Are we hitting this described behavior: http://paradigm4.github.io/shim/help.html#orphaned-sessions

In general, I am looking for suggestions about what we might do to avoid such an issue in the future? 

### Config etc. 

Here is the shim config file:

```sh
ports=8083
scidbport=1239
instance=0
tmp=/scidb_data0/shim_dir/
user=sa-prd-scidb
#max_sessions=50
#timeout=60
aio=1
```

Here are the number of open files in the shim directory:

```sh
ls //scidb_data0/shim_dir/shim_output_buf_* | wc -l
# 30
```

Version info
```
shim -version
# SciDB Version: 18.1.13
# Shim Commit: 8a427c0

yum list installed | grep extra-scidb-libs
# extra-scidb-libs-18.1.x86_64 6-1                     @paradigm4-extra
```

I will keep a copy of the shim log file available and can share that privately if you think it might help.

**Comment by rvernica** [comment]
This specific error is not actually generated by the Shim code, but by the Mongoose library (the embedded web server used in Shim). The error is triggered when trying to open one more file and reaches the limit.

This is not directly related to _Orphaned Sessions_ and increasing `max_sessions` would not help. If Shim runs out of sessions, you will get a different error code and error message:
```
Status Code: 503 Service Unavailable
Message: Out of resources
```

So, I would suggest increasing the file limits in `/etc/security/limits.conf` and confirming the new limits with `ulimit`.

**Comment by ksens** [comment]
Copying @apoliakov 's notes for future reference:

> Often times the linux "too many open files" error can be overcome by adjusting `/etc/security/limits.conf`. You can just set it to a high number.
> 
> These are the numbers I use at a couple of places. They are tied to the linux user `scidb`:
> ```
> $ cat /etc/security/limits.conf | grep scidb
> scidb        hard nofile 102400
> scidb        soft nofile 102400
> ```
> 
> They don't take effect until you establish a new session.
> You can run `ulimit` to confirm they are in effect.

**Comment by apoliakov** [comment]
Make sure you run `ulimit -a`
I sent you more details in email

**Comment by ksens** [comment]
Again, storing for reference:

Here is the output of `ulimit -a`
```
# ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 250950
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1024000          # <== this is what we care about
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 4096
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```

Also, suggested by our IT principal at [customer A](https://github.com/Paradigm4/cs-private-notes-space/tree/master/customer-code-names): 

Instead of modifying the original `/etc/security/limits.conf` file, it is a better practise to modify via the `limits.d` directory:

```
# cat /etc/security/limits.d/40-scidb.conf

# Default limits for scidb open files

sa-prd-scidb       hard    nofile     1024000
sa-prd-scidb       soft    nofile     1024000
```

Closing issue.
